name: Verify Build

on:
  workflow_call:
    inputs:
      changed-files:
        required: true
        type: string
        description: Build relenv python builds

jobs:

  build_linux:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 3.10.18
          - 3.11.13
          - 3.12.11
          - 3.13.5
        host:
          - x86_64
          - aarch64
        include:
          - host: x86_64
            target: x86_64
          - host: aarch64
            target: aarch64

    name: "Verify Linux"
    runs-on:
      - ${{ (contains(matrix.host, 'x86_64') && 'ubuntu-24.04') || 'ubuntu-24.04-arm' }}

    env:
      RELENV_DATA: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison python3-all patchelf swig cmake libldap2-dev libsasl2-dev ldap-utils libssl-dev pkg-config libvirt-dev default-libmysqlclient-dev python3-virtualenv
          virtualenv venv
          venv/bin/python3 -m pip install nox ppbt

      - name: Python Version
        run: |
          venv/bin/python3 --version
          venv/bin/python3 -c 'import os; print(os.name)'

      - name: "Download artifact: build/${{ matrix.version }}-${{ matrix.target }}-linux-gnu.tar.xz"
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.version }}-${{ matrix.target }}-linux-gnu.tar.xz
          path: build/

      - name: Verify Build
        if: ${{ matrix.host == matrix.target }}
        run: |
          venv/bin/python3 -m nox -e tests -- -s tests/test_verify_build.py

      - name: Linux Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.version }}-${{ matrix.host }}-${{ matrix.target }}-linux-gnu-logs
          path: logs/*
          retention-days: 5

  test_macos_13_x86_64:
    name: "Verify MacOS"

    runs-on: macos-13

    strategy:
      fail-fast: false
      matrix:
        version:
          - 3.10.18
          - 3.11.13
          - 3.12.11
          - 3.13.5
        arch:
          - x86_64

    env:
      RELENV_DATA: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show environment
        run: |
          env

      - name: Install nox
        run: |
          pip3 install nox

      - name: "Download artifact: build/${{ matrix.version }}-${{ matrix.arch }}-macos.tar.xz"
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.version }}-${{ matrix.arch }}-macos.tar.xz
          path: build/

      - name: Verify Build
        run: |
          python3 -m nox -e tests -- tests/test_verify_build.py

      - name: MacOS Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.version }}-${{ matrix.arch }}-macos-logs
          path: logs/*
          retention-days: 5

  test_macos_13_arm64:
    name: "Verify MacOS (M1)"

    runs-on: macos-15

    strategy:
      fail-fast: false
      matrix:
        version:
          - 3.10.18
          - 3.11.13
          - 3.12.11
          - 3.13.5
        arch:
          - arm64

    env:
      RELENV_DATA: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Patch include
        run: |
          sudo mkdir /tmp/local
          sudo mv -f /usr/local/* /tmp/local/

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show environment
        run: |
          env

      - name: Install nox
        run: |
          brew install nox

      - name: "Download artifact: build/${{ matrix.version }}-${{ matrix.arch }}-macos.tar.xz"
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.version }}-${{ matrix.arch }}-macos.tar.xz
          path: build/

      - name: Verify Build
        run: |
          nox -e tests -- tests/test_verify_build.py

      - name: MacOS Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.version }}-${{ matrix.arch }}-macos-logs
          path: logs/*
          retention-days: 5


  test_windows:
    name: "Verify Windows"
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - 3.10.18
          - 3.11.13
          - 3.12.11
          - 3.13.5
        arch:
          - amd64
          - x86

    env:
      RELENV_DATA: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install VS Build Tools
        run: |
          relenv/_scripts/install_vc_build.ps1 -CICD

      - name: Install nox
        run: |
          pip3 install nox

      - name: "Download artifact: build/${{ matrix.version }}-${{ matrix.arch }}-win.tar.xz"
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.version }}-${{ matrix.arch }}-win.tar.xz
          path: build/

      - name: Verify Build
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          nox -e tests -- tests/test_verify_build.py

      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.version }}-${{ matrix.arch }}-windows-logs
          path: logs/*
          retention-days: 5
